### ISSUE TITLE
Specify a license

### ISSUE THREAD

**Issue by somazx** [PauloPaixao/hse-font#1]
Thank you for doing this, we'd love to use it in our project. Unfortunately code without a specified license it considered copyright. Assuming you intended for others to use the hse-font, could you specify a license? Thanks!

https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by PauloPaixao** [comment]
Feel free to use it. ;)

**Comment by somazx** [comment]
Awesome! Thanks very much.
